version: "3.8"

services:
  #Authentication Services
  db-account:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=authenticationdb
      - MYSQL_ROOT_PASSWORD=dbadmin

    ports:
      - "3300:3306"
    volumes:
      - db_authentication:/var/lib/mysql

volumes:
  db_authentication:
    driver: local
