spring:
  config:
    activate:
      on-profile: dev

  main:
    allow-bean-definition-overriding: true

  data:
    cassandra:
      contact-points: "localhost"
      port: 9042
      keyspace-name: authentication
      schema-action: create_if_not_exists
      local-datacenter: datacenter1

jwt:
  secret: "top_secret"
---
spring:
  config:
    activate:
      on-profile: prod

  main:
    allow-bean-definition-overriding: ${SPRING_ALLOW_BEAN_DEFINITION_OVERRIDING}
  data:
    cassandra:
      contact-points: ${DB_CONTACT_POINTS}
      port: ${DB_PORT}
      keyspace-name: ${DB_AUTHENTICATION_KEYSPACE}
      schema-action: ${DB_SCHEME_ACTION}
      local-datacenter: ${DB_DATACENTER}
      request:
        timeout: ${DB_REQUEST_TIMEOUT}

jwt:
  secret: ${JWT_SECRET}

#server:
#  port: ${AUTHENTICATION_SERVICE_PORT}