spring:
  application:
    name: authentication

  datasource:
    url: jdbc:mysql://localhost:3300/authenticationdb
#  url: ${ACCOUNT_DB_URL}
    username: root
    password: dbadmin
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
      #      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always


  main:
    allow-bean-definition-overriding: true

server:
  port: 5001
#  port: ${ACCOUNT_SERVICE_PORT}