---
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config

data:
  MYSQL_ROOT_PASSWORD: dbadmin

  AUTHENTICATION_DB_URL: jdbc:mysql://authenticationdb-svc:5001/authenticationdb
  AUTHENTICATION_SERVICE_URL: http://authentication-service:5501
  AUTHENTICATION_SERVICE_PORT: "5501"


