---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  type: NodePort
  selector:
    app: authentication
  ports:
    - protocol: TCP
      port: 5501
      nodePort: 30501
      targetPort: 5501