---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-deployment
  labels:
    app: authentication
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication-service
          image: phucthaihg/authentication:1.0
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: http
              containerPort: 5501
          envFrom:
            - configMapRef:
                name: common-config
      terminationGracePeriodSeconds: 1
