apiVersion: v1
kind: ConfigMap
metadata:
  name: authenticationdb-config
data:
  authenticationdb.sql: |-
    DROP DATABASE IF EXISTS authenticationdb;
    CREATE DATABASE authenticationdb;
    USE authenticationdb;
    
    
    create table roles
    (
    id   int auto_increment
    primary key,
    role varchar(255) null,
    constraint UK_g50w4r0ru3g9uf6i6fr4kpro8
    unique (role)
    );
    
    
    create table users
    (
    id         int auto_increment
    primary key,
    email      varchar(255) null,
    first_name varchar(255) null,
    last_name  varchar(255) null,
    password   varchar(255) null,
    constraint UK_6dotkott2kjsp8vw4d0m25fb7
    unique (email)
    );
    
    
    create table users_roles
    (
    user_id  int not null,
    roles_id int not null,
    primary key (user_id, roles_id),
    constraint FK2o0jvgh89lemvvo17cbqvdxaa
    foreign key (user_id) references users (id),
    constraint FKa62j07k5mhgifpp955h37ponj
    foreign key (roles_id) references roles (id)
    );
    
    
    create table roles_users
    (
    role_id  int not null,
    users_id int not null,
    primary key (role_id, users_id),
    constraint FK4glr8k8swy5nti6n5x35ofucj
    foreign key (users_id) references users (id),
    constraint FKsmos02hm32191ogexm2ljik9x
    foreign key (role_id) references roles (id)
    );

    INSERT INTO users(email, first_name, last_name, password)
    VALUES
    ('phat@gmail.com', 'Phat', 'Nguyen', '$2a$10$u5xPEnqTU3lcPPItCotEf./kp4k2zj4Q9Mnko5W4nBca4pvhLs7Zq'),
    ('john@gmail.com', 'John', 'Smith', '$2a$10$u5xPEnqTU3lcPPItCotEf./kp4k2zj4Q9Mnko5W4nBca4pvhLs7Zq'),
    ('david@gmail.com', 'David', 'Nguyen', '$2a$10$u5xPEnqTU3lcPPItCotEf./kp4k2zj4Q9Mnko5W4nBca4pvhLs7Zq'),
    ('smith@gmail.com', 'Smith', 'Nguyen', '$2a$10$u5xPEnqTU3lcPPItCotEf./kp4k2zj4Q9Mnko5W4nBca4pvhLs7Zq'),
    ('adam@gmail.com', 'Adam', 'John', '$2a$10$u5xPEnqTU3lcPPItCotEf./kp4k2zj4Q9Mnko5W4nBca4pvhLs7Zq'),
    ('michael@gmail.com', 'Michael', 'Mike', '$2a$10$u5xPEnqTU3lcPPItCotEf./kp4k2zj4Q9Mnko5W4nBca4pvhLs7Zq');
    --
    -- -- ROLE
    INSERT INTO roles(role)
    VALUES
    ('ADMIN'),
    ('USER');
    --
    INSERT INTO users_roles(user_id, roles_id)
    VALUES
    (1, 1),
    (1, 2),
    (2, 1),
    (3, 1),
    (4, 2),
    (5, 2),
    (5, 1),
    (6, 2);
  
  
  
  
